database:
  db_path: trading_bot.sqlite
logging:
  level: INFO
  log_dir: logs
notifications:
  email:
    enabled: true
    password: czucverjkbtaffsb
    recipient: tradingmaster925@gmail.com
    report_recipient: rionalphonso25@gmail.com
    sender: tradingmaster925@gmail.com
  telegram:
    bot_token: 8873432906:AAG4F3Hhon5Cz8uYmqD6adHfPHN4mAs0qL0
    chat_id: '1920085567'
    enabled: true
system:
  auditor_enabled: true
  auto_off_enabled: false
  auto_on_enabled: true
trading:
  symbol: XAUUSD.m
  timeframe: M5
  initial_capital: 1110
  indicators:
    ema_enabled: false
    ema_fast: 9
    ema_slow: 21
  sessions_ist:
  - start: '20:00'
    end: '22:30'
  - start: '10:00'
    end: '17:30'
  direction: BOTH
  days_mode: '24_5'
  risk_percent: 0.1
  tp_points: 10000
  sl_points: 1000
